name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.heroku.com/customerOrderService/web

      - name: Release to Heroku
        run: heroku container:release web --app customerOrderService
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
